trunk-version = "^0.21.0"

[build]
target = "index.html"
dist = "dist"
public_url = "/"
filehash = false
minify = "never"
no_sri = true
no_default_features = true
features = ["web", "markdown-demo"]

[watch]
watch = [
  "index.html",
  "Trunk.toml",
  "../Cargo.toml",
  "../src",
  "../../sui/Cargo.toml",
  "../../sui/src",
  "../../sui-core/Cargo.toml",
  "../../sui-core/src",
  "../../sui-layout/Cargo.toml",
  "../../sui-layout/src",
  "../../sui-platform/Cargo.toml",
  "../../sui-platform/src",
  "../../sui-render-wgpu/Cargo.toml",
  "../../sui-render-wgpu/src",
  "../../sui-runtime/Cargo.toml",
  "../../sui-runtime/src",
  "../../sui-runtime/assets",
  "../../sui-scene/Cargo.toml",
  "../../sui-scene/src",
  "../../sui-text/Cargo.toml",
  "../../sui-text/src",
  "../../sui-text/assets",
  "../../sui-widgets/Cargo.toml",
  "../../sui-widgets/src",
  "../../../Cargo.lock",
  "../../../Cargo.toml",
]
ignore = ["dist"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false
