// Generated by `cargo xtask bindings generate` from bindings/widgets.sui and bindings/templates/python_widgets.rs.in.
// Do not edit by hand.

// Python widget bindings.

#[pyclass(name = "TextSpan", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PyTextSpan {
    inner: BindingTextSpan,
}

#[pymethods]
impl PyTextSpan {
    #[new]
    #[pyo3(signature = (text, color=None, font_size=None, line_height=None, font=None, weight=None, style=None, stretch=None))]
    pub fn new(
        text: String,
        color: Option<PyColor>,
        font_size: Option<f32>,
        line_height: Option<f32>,
        font: Option<PyRef<'_, PyFontHandle>>,
        weight: Option<u16>,
        style: Option<&str>,
        stretch: Option<&str>,
    ) -> PyResult<Self> {
        Ok(Self {
            inner: BindingTextSpan::new(
                text,
                py_text_style(color, font_size, line_height, font, weight, style, stretch)?,
            ),
        })
    }

    #[getter]
    pub fn text(&self) -> &str {
        &self.inner.text
    }

    fn __repr__(&self) -> String {
        format!("TextSpan({:?})", self.inner.text)
    }
}

#[pyclass(name = "StatusBarSegment", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PyStatusBarSegment {
    inner: BindingStatusBarSegment,
}

#[pymethods]
impl PyStatusBarSegment {
    #[new]
    #[pyo3(signature = (text, tone="neutral", min_width=None, expand=false))]
    pub fn new(
        text: &Bound<'_, PyAny>,
        tone: &str,
        min_width: Option<f32>,
        expand: bool,
    ) -> PyResult<Self> {
        Ok(Self {
            inner: BindingStatusBarSegment::new(
                binding_text_from_py(text)?,
                py_semantic_tone(tone)?,
                min_width,
                expand,
            ),
        })
    }

    fn __repr__(&self) -> String {
        format!("{:?}", self.inner)
    }
}

#[pyclass(name = "SegmentedControlItem", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PySegmentedControlItem {
    inner: BindingSegmentedControlItem,
}

#[pymethods]
impl PySegmentedControlItem {
    #[new]
    #[pyo3(signature = (label, semantic_name=None, description=None, disabled=false))]
    pub fn new(
        label: String,
        semantic_name: Option<String>,
        description: Option<String>,
        disabled: bool,
    ) -> Self {
        Self {
            inner: BindingSegmentedControlItem::new(label, semantic_name, description, disabled),
        }
    }

    fn __repr__(&self) -> String {
        format!("{:?}", self.inner)
    }
}

#[pyclass(name = "TableColumn", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PyTableColumn {
    inner: BindingTableColumn,
}

#[pymethods]
impl PyTableColumn {
    #[new]
    #[pyo3(signature = (title, width=None, min_width=None, alignment="start", numeric=false))]
    pub fn new(
        title: String,
        width: Option<f32>,
        min_width: Option<f32>,
        alignment: &str,
        numeric: bool,
    ) -> PyResult<Self> {
        Ok(Self {
            inner: BindingTableColumn::new(
                title,
                width,
                min_width,
                py_table_column_alignment(alignment)?,
                numeric,
            ),
        })
    }

    fn __repr__(&self) -> String {
        format!("{:?}", self.inner)
    }
}

#[pyclass(name = "TableRow", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PyTableRow {
    inner: BindingTableRow,
}

#[pymethods]
impl PyTableRow {
    #[new]
    pub fn new(cells: Vec<String>) -> Self {
        Self {
            inner: BindingTableRow::new(cells),
        }
    }

    fn __repr__(&self) -> String {
        format!("{:?}", self.inner)
    }
}

#[pyclass(name = "TreeItem", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PyTreeItem {
    inner: BindingTreeItem,
}

#[pymethods]
impl PyTreeItem {
    #[new]
    #[pyo3(signature = (label, detail=None, expanded=false, disabled=false, children=None))]
    pub fn new(
        label: String,
        detail: Option<String>,
        expanded: bool,
        disabled: bool,
        children: Option<&Bound<'_, PyAny>>,
    ) -> PyResult<Self> {
        let children = children.map(extract_tree_items).transpose()?.unwrap_or_default();
        Ok(Self {
            inner: BindingTreeItem::new(label, detail, expanded, disabled, children),
        })
    }

    fn __repr__(&self) -> String {
        format!("{:?}", self.inner)
    }
}

#[pyclass(name = "LayerListItem", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PyLayerListItem {
    inner: BindingLayerListItem,
}

#[pymethods]
impl PyLayerListItem {
    #[new]
    #[pyo3(signature = (label, detail=None, visible=true, locked=false, disabled=false))]
    pub fn new(
        label: String,
        detail: Option<String>,
        visible: bool,
        locked: bool,
        disabled: bool,
    ) -> Self {
        Self {
            inner: BindingLayerListItem::new(label, detail, visible, locked, disabled),
        }
    }

    fn __repr__(&self) -> String {
        format!("{:?}", self.inner)
    }
}

#[pyclass(name = "MenuItem", module = "sui", skip_from_py_object)]
#[derive(Debug, Clone)]
pub struct PyMenuItem {
    inner: BindingMenuItem,
}

#[pymethods]
impl PyMenuItem {
    #[new]
    #[pyo3(signature = (label, shortcut=None, disabled=false, destructive=false, separator_before=false))]
    pub fn new(
        label: String,
        shortcut: Option<String>,
        disabled: bool,
        destructive: bool,
        separator_before: bool,
    ) -> Self {
        Self {
            inner: BindingMenuItem::new(label, shortcut, disabled, destructive, separator_before),
        }
    }

    fn __repr__(&self) -> String {
        format!("{:?}", self.inner)
    }
}

#[pyfunction(name = "Label")]
pub fn py_label(value: &Bound<'_, PyAny>) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::label(
        binding_text_from_py(value)?,
    )))
}

#[pyfunction(name = "Button")]
#[pyo3(signature = (label, on_press=None))]
pub fn py_button(label: &Bound<'_, PyAny>, on_press: Option<Py<PyAny>>) -> PyResult<PyWidget> {
    let action = on_press.map(|callback| {
        BindingAction::new(move || {
            Python::attach(|py| {
                callback
                    .call0(py)
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::button(
        binding_text_from_py(label)?,
        action,
    )))
}

#[pyfunction(name = "Icon")]
#[pyo3(signature = (glyph, label=None, size=None, color=None))]
pub fn py_icon(
    glyph: &str,
    label: Option<String>,
    size: Option<f32>,
    color: Option<PyColor>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::icon(
        py_icon_glyph(glyph)?,
        label,
        size,
        color.map(Into::into),
    )))
}

#[pyfunction(name = "IconButton")]
#[pyo3(signature = (glyph, label, selected=None, enabled=None, size=None, icon_size=None, description=None, on_press=None))]
pub fn py_icon_button(
    glyph: &str,
    label: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    enabled: Option<&Bound<'_, PyAny>>,
    size: Option<f32>,
    icon_size: Option<f32>,
    description: Option<String>,
    on_press: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(false));
    let enabled = enabled
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(true));
    let action = on_press.map(|callback| {
        BindingAction::new(move || {
            Python::attach(|py| {
                callback
                    .call0(py)
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::icon_button(
        py_icon_glyph(glyph)?,
        binding_text_from_py(label)?,
        selected,
        enabled,
        size,
        icon_size,
        description,
        action,
    )))
}

#[pyfunction(name = "Link")]
#[pyo3(signature = (label, url, semantic_name=None, enabled=None, on_open=None))]
pub fn py_link(
    label: &Bound<'_, PyAny>,
    url: &Bound<'_, PyAny>,
    semantic_name: Option<String>,
    enabled: Option<&Bound<'_, PyAny>>,
    on_open: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let enabled = enabled
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(true));
    let action = on_open.map(|callback| {
        BindingStringAction::new(move |url| {
            Python::attach(|py| {
                callback
                    .call1(py, (url,))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::link(
        binding_text_from_py(label)?,
        binding_text_from_py(url)?,
        semantic_name,
        enabled,
        action,
    )))
}

#[pyfunction(name = "Checkbox")]
#[pyo3(signature = (label, checked=None, on_toggle=None))]
pub fn py_checkbox(
    label: &Bound<'_, PyAny>,
    checked: Option<&Bound<'_, PyAny>>,
    on_toggle: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let checked = checked
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(false));
    let action = on_toggle.map(|callback| {
        BindingBoolAction::new(move |value| {
            Python::attach(|py| {
                callback
                    .call1(py, (value,))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::checkbox(
        binding_text_from_py(label)?,
        checked,
        action,
    )))
}

#[pyfunction(name = "Switch")]
#[pyo3(signature = (label, on=None, on_toggle=None))]
pub fn py_switch(
    label: &Bound<'_, PyAny>,
    on: Option<&Bound<'_, PyAny>>,
    on_toggle: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let on = on
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(false));
    let action = on_toggle.map(|callback| {
        BindingBoolAction::new(move |value| {
            Python::attach(|py| {
                callback
                    .call1(py, (value,))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::switch(
        binding_text_from_py(label)?,
        on,
        action,
    )))
}

#[pyfunction(name = "RadioButton")]
#[pyo3(signature = (label, selected=None, on_select=None))]
pub fn py_radio_button(
    label: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    on_select: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(false));
    let action = on_select.map(|callback| {
        BindingAction::new(move || {
            Python::attach(|py| {
                callback
                    .call0(py)
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::radio_button(
        binding_text_from_py(label)?,
        selected,
        action,
    )))
}

#[pyfunction(name = "RadioGroup")]
#[pyo3(signature = (name, options, selected=None, on_change=None))]
pub fn py_radio_group(
    name: &Bound<'_, PyAny>,
    options: Vec<String>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::radio_group(
        binding_text_from_py(name)?,
        options,
        selected,
        action,
    )))
}

#[pyfunction(name = "SegmentedControl")]
#[pyo3(signature = (name, items, selected=None, on_change=None))]
pub fn py_segmented_control(
    name: &Bound<'_, PyAny>,
    items: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::segmented_control(
        binding_text_from_py(name)?,
        extract_segmented_control_items(items)?,
        selected,
        action,
    )))
}

fn py_breadcrumb_widget(
    name: &Bound<'_, PyAny>,
    items: Vec<String>,
    current: Option<&Bound<'_, PyAny>>,
    on_activate: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let current = current.map(binding_number_from_py).transpose()?;
    let action = on_activate.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::breadcrumb(
        binding_text_from_py(name)?,
        items,
        current,
        action,
    )))
}

#[pyfunction(name = "Breadcrumb")]
#[pyo3(signature = (name, items, current=None, on_activate=None))]
pub fn py_breadcrumb(
    name: &Bound<'_, PyAny>,
    items: Vec<String>,
    current: Option<&Bound<'_, PyAny>>,
    on_activate: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    py_breadcrumb_widget(name, items, current, on_activate)
}

#[pyfunction(name = "PathBar")]
#[pyo3(signature = (name, items, current=None, on_activate=None))]
pub fn py_path_bar(
    name: &Bound<'_, PyAny>,
    items: Vec<String>,
    current: Option<&Bound<'_, PyAny>>,
    on_activate: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    py_breadcrumb_widget(name, items, current, on_activate)
}

#[pyfunction(name = "ListView")]
#[pyo3(signature = (name, items, selected=None, on_change=None))]
pub fn py_list_view(
    name: &Bound<'_, PyAny>,
    items: Vec<String>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::list_view(
        binding_text_from_py(name)?,
        items,
        selected,
        action,
    )))
}

fn py_table_widget(
    name: &Bound<'_, PyAny>,
    columns: &Bound<'_, PyAny>,
    rows: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::table(
        binding_text_from_py(name)?,
        extract_table_columns(columns)?,
        extract_table_rows(rows)?,
        selected,
        action,
    )))
}

#[pyfunction(name = "Table")]
#[pyo3(signature = (name, columns, rows, selected=None, on_change=None))]
pub fn py_table(
    name: &Bound<'_, PyAny>,
    columns: &Bound<'_, PyAny>,
    rows: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    py_table_widget(name, columns, rows, selected, on_change)
}

#[pyfunction(name = "DataGrid")]
#[pyo3(signature = (name, columns, rows, selected=None, on_change=None))]
pub fn py_data_grid(
    name: &Bound<'_, PyAny>,
    columns: &Bound<'_, PyAny>,
    rows: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    py_table_widget(name, columns, rows, selected, on_change)
}

#[pyfunction(name = "Slider")]
#[pyo3(signature = (name, value=None, min_value=0.0, max_value=1.0, step=0.01, on_change=None))]
pub fn py_slider(
    name: &Bound<'_, PyAny>,
    value: Option<&Bound<'_, PyAny>>,
    min_value: f64,
    max_value: f64,
    step: f64,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let value = value
        .map(binding_number_from_py)
        .transpose()?
        .unwrap_or(BindingNumber::Static(0.0));
    let action = on_change.map(|callback| {
        BindingNumberAction::new(move |value| {
            Python::attach(|py| {
                callback
                    .call1(py, (value,))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::slider(
        binding_text_from_py(name)?,
        value,
        min_value,
        max_value,
        step,
        action,
    )))
}

#[pyfunction(name = "NumberInput")]
#[pyo3(signature = (name, value=None, min_value=None, max_value=None, step=1.0, precision=2, on_change=None))]
pub fn py_number_input(
    name: &Bound<'_, PyAny>,
    value: Option<&Bound<'_, PyAny>>,
    min_value: Option<f64>,
    max_value: Option<f64>,
    step: f64,
    precision: usize,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let value = value
        .map(binding_number_from_py)
        .transpose()?
        .unwrap_or(BindingNumber::Static(0.0));
    let action = on_change.map(|callback| {
        BindingNumberAction::new(move |value| {
            Python::attach(|py| {
                callback
                    .call1(py, (value,))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::number_input(
        binding_text_from_py(name)?,
        value,
        min_value.unwrap_or(f64::NEG_INFINITY),
        max_value.unwrap_or(f64::INFINITY),
        step,
        precision,
        action,
    )))
}

#[pyfunction(name = "Select")]
#[pyo3(signature = (name, options, selected=None, placeholder=None, on_change=None))]
pub fn py_select(
    name: &Bound<'_, PyAny>,
    options: Vec<String>,
    selected: Option<&Bound<'_, PyAny>>,
    placeholder: Option<String>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::select(
        binding_text_from_py(name)?,
        options,
        selected,
        placeholder,
        action,
    )))
}

#[pyfunction(name = "ProgressBar")]
#[pyo3(signature = (name, value=None, min_value=0.0, max_value=1.0, show_value=false))]
pub fn py_progress_bar(
    name: &Bound<'_, PyAny>,
    value: Option<&Bound<'_, PyAny>>,
    min_value: f64,
    max_value: f64,
    show_value: bool,
) -> PyResult<PyWidget> {
    let value = value
        .map(binding_number_from_py)
        .transpose()?
        .unwrap_or(BindingNumber::Static(0.0));
    Ok(PyWidget::from_binding(BindingWidget::progress_bar(
        binding_text_from_py(name)?,
        value,
        min_value,
        max_value,
        show_value,
    )))
}

#[pyfunction(name = "SignalMeter")]
#[pyo3(signature = (name, active=None, description=None, bars=12, size=None))]
pub fn py_signal_meter(
    name: &Bound<'_, PyAny>,
    active: Option<&Bound<'_, PyAny>>,
    description: Option<String>,
    bars: usize,
    size: Option<PySize>,
) -> PyResult<PyWidget> {
    let active = active
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(false));
    Ok(PyWidget::from_binding(BindingWidget::signal_meter(
        binding_text_from_py(name)?,
        active,
        description,
        bars,
        size.map(Into::into),
    )))
}

#[pyfunction(name = "StatusBadge")]
#[pyo3(signature = (label, tone="neutral", icon=None, min_width=None))]
pub fn py_status_badge(
    label: &Bound<'_, PyAny>,
    tone: &str,
    icon: Option<String>,
    min_width: Option<f32>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::status_badge(
        binding_text_from_py(label)?,
        py_semantic_tone(tone)?,
        icon.as_deref().map(py_icon_glyph).transpose()?,
        min_width,
    )))
}

#[pyfunction(name = "StatusBar")]
#[pyo3(signature = (segments, name=None, description=None, height=None))]
pub fn py_status_bar(
    segments: &Bound<'_, PyAny>,
    name: Option<String>,
    description: Option<&Bound<'_, PyAny>>,
    height: Option<f32>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::status_bar(
        extract_status_bar_segments(segments)?,
        name,
        description.map(binding_text_from_py).transpose()?,
        height,
    )))
}

#[pyfunction(name = "DetailRow")]
#[pyo3(signature = (label, value, max_value_lines=None))]
pub fn py_detail_row(
    label: &Bound<'_, PyAny>,
    value: &Bound<'_, PyAny>,
    max_value_lines: Option<usize>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::detail_row(
        binding_text_from_py(label)?,
        binding_text_from_py(value)?,
        max_value_lines,
    )))
}

#[pyfunction(name = "BusyIndicator")]
#[pyo3(signature = (name, label=None, size=20.0))]
pub fn py_busy_indicator(
    name: &Bound<'_, PyAny>,
    label: Option<&Bound<'_, PyAny>>,
    size: f32,
) -> PyResult<PyWidget> {
    let label = label.map(binding_text_from_py).transpose()?;
    Ok(PyWidget::from_binding(BindingWidget::busy_indicator(
        binding_text_from_py(name)?,
        label,
        size,
    )))
}

#[pyfunction(name = "TextInput")]
#[pyo3(signature = (name, value=None, placeholder=None, on_change=None))]
pub fn py_text_input(
    name: &Bound<'_, PyAny>,
    value: Option<&Bound<'_, PyAny>>,
    placeholder: Option<String>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let value = value
        .map(binding_text_from_py)
        .transpose()?
        .unwrap_or_else(|| BindingText::Static(String::new()));
    let action = on_change.map(|callback| {
        BindingStringAction::new(move |value| {
            Python::attach(|py| {
                callback
                    .call1(py, (value,))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::text_input(
        binding_text_from_py(name)?,
        value,
        placeholder,
        action,
    )))
}

#[pyfunction(name = "TextArea")]
#[pyo3(signature = (name, value=None, placeholder=None, on_change=None))]
pub fn py_text_area(
    name: &Bound<'_, PyAny>,
    value: Option<&Bound<'_, PyAny>>,
    placeholder: Option<String>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let value = value
        .map(binding_text_from_py)
        .transpose()?
        .unwrap_or_else(|| BindingText::Static(String::new()));
    let action = on_change.map(|callback| {
        BindingStringAction::new(move |value| {
            Python::attach(|py| {
                callback
                    .call1(py, (value,))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::text_area(
        binding_text_from_py(name)?,
        value,
        placeholder,
        action,
    )))
}

#[pyfunction(name = "RichText")]
#[pyo3(signature = (spans, semantic_name=None, min_width=0.0, min_height=0.0))]
pub fn py_rich_text(
    spans: &Bound<'_, PyAny>,
    semantic_name: Option<String>,
    min_width: f32,
    min_height: f32,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::rich_text(
        extract_text_spans(spans)?,
        semantic_name,
        min_width,
        min_height,
    )))
}

#[pyfunction(name = "Image")]
#[pyo3(signature = (image, label=None, fit="contain", size=None))]
pub fn py_image(
    image: PyRef<'_, PyImageHandle>,
    label: Option<String>,
    fit: &str,
    size: Option<PySize>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::image(
        image.inner,
        label,
        py_image_fit(fit)?,
        size.map(Into::into),
    )))
}

#[pyfunction(name = "ColorSwatch")]
#[pyo3(signature = (name, color, size=None, read_only=false, on_press=None))]
pub fn py_color_swatch(
    name: &str,
    color: PyColor,
    size: Option<PySize>,
    read_only: bool,
    on_press: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let action = on_press.map(|callback| {
        BindingAction::new(move || {
            Python::attach(|py| {
                callback
                    .call0(py)
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::color_swatch(
        name,
        color.into(),
        size.map(Into::into),
        read_only,
        action,
    )))
}

#[pyfunction(name = "Separator")]
#[pyo3(signature = (axis="horizontal", name=None, inset=0.0, thickness=None, length=None))]
pub fn py_separator(
    axis: &str,
    name: Option<String>,
    inset: f32,
    thickness: Option<f32>,
    length: Option<f32>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::separator(
        py_axis(axis)?,
        name,
        inset,
        thickness,
        length,
    )))
}

#[pyfunction(name = "EmptyState")]
#[pyo3(signature = (title, description, name=None, detail=None, icon=None, action=None, background=None, transparent=false))]
pub fn py_empty_state(
    title: &str,
    description: &str,
    name: Option<String>,
    detail: Option<String>,
    icon: Option<String>,
    action: Option<PyRef<'_, PyWidget>>,
    background: Option<PyColor>,
    transparent: bool,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::empty_state(
        title,
        description,
        name,
        detail,
        icon.as_deref().map(py_icon_glyph).transpose()?,
        action
            .as_ref()
            .map(|widget| widget.binding_widget())
            .transpose()?,
        background.map(Into::into),
        transparent,
    )))
}

#[pyfunction(name = "Surface")]
#[pyo3(signature = (child, role="panel", name=None, border=None, elevation=None, radius=None, padding=None, fill_width=false, fill_height=false))]
pub fn py_surface(
    child: PyRef<'_, PyWidget>,
    role: &str,
    name: Option<String>,
    border: Option<String>,
    elevation: Option<String>,
    radius: Option<f32>,
    padding: Option<f32>,
    fill_width: bool,
    fill_height: bool,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::surface(
        child.binding_widget()?,
        py_surface_role(role)?,
        name,
        border.as_deref().map(py_surface_border).transpose()?,
        elevation.as_deref().map(py_surface_elevation).transpose()?,
        radius,
        padding,
        fill_width,
        fill_height,
    )))
}

#[pyfunction(name = "Toolbar")]
#[pyo3(signature = (children, axis="horizontal", name=None, extent=None, padding=None, spacing=None, background=None, divider=true))]
pub fn py_toolbar(
    children: &Bound<'_, PyAny>,
    axis: &str,
    name: Option<String>,
    extent: Option<f32>,
    padding: Option<f32>,
    spacing: Option<f32>,
    background: Option<PyColor>,
    divider: bool,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::toolbar(
        extract_binding_widgets(children)?,
        py_axis(axis)?,
        name,
        extent,
        padding,
        spacing,
        background.map(Into::into),
        divider,
    )))
}

#[pyfunction(name = "Column")]
#[pyo3(signature = (children, gap=0.0))]
pub fn py_column(children: &Bound<'_, PyAny>, gap: f32) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::column(
        extract_binding_widgets(children)?,
        gap,
    )))
}

#[pyfunction(name = "Row")]
#[pyo3(signature = (children, gap=0.0))]
pub fn py_row(children: &Bound<'_, PyAny>, gap: f32) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::row(
        extract_binding_widgets(children)?,
        gap,
    )))
}

#[pyfunction(name = "ScrollView")]
#[pyo3(signature = (child, axes="vertical", name=None))]
pub fn py_scroll_view(
    child: PyRef<'_, PyWidget>,
    axes: &str,
    name: Option<String>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::scroll_view(
        child.binding_widget()?,
        py_scroll_axes(axes)?,
        name,
    )))
}

#[pyfunction(name = "ExternalSurface")]
#[pyo3(signature = (texture, desired_size=None, name=None))]
pub fn py_external_surface(
    texture: PyRef<'_, PyExternalTextureDescriptor>,
    desired_size: Option<PySize>,
    name: Option<String>,
) -> PyResult<PyWidget> {
    BindingWidget::external_surface(texture.inner.clone(), desired_size.map(Into::into), name)
        .map(PyWidget::from_binding)
        .map_err(py_external_texture_error)
}

#[pyfunction(name = "TreeView")]
#[pyo3(signature = (name, items, selected=None, on_change=None))]
pub fn py_tree_view(
    name: &Bound<'_, PyAny>,
    items: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::tree_view(
        binding_text_from_py(name)?,
        extract_tree_items(items)?,
        selected,
        action,
    )))
}

#[pyfunction(name = "LayerList")]
#[pyo3(signature = (name, items, selected=None, on_change=None))]
pub fn py_layer_list(
    name: &Bound<'_, PyAny>,
    items: &Bound<'_, PyAny>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::layer_list(
        binding_text_from_py(name)?,
        extract_layer_list_items(items)?,
        selected,
        action,
    )))
}

#[pyfunction(name = "Menu")]
#[pyo3(signature = (name, items, highlighted=None, on_activate=None))]
pub fn py_menu(
    name: &Bound<'_, PyAny>,
    items: &Bound<'_, PyAny>,
    highlighted: Option<&Bound<'_, PyAny>>,
    on_activate: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let highlighted = highlighted.map(binding_number_from_py).transpose()?;
    let action = on_activate.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::menu(
        binding_text_from_py(name)?,
        extract_menu_items(items)?,
        highlighted,
        action,
    )))
}

#[pyfunction(name = "TabBar")]
#[pyo3(signature = (name, tabs, selected=None, on_change=None))]
pub fn py_tab_bar(
    name: &Bound<'_, PyAny>,
    tabs: Vec<String>,
    selected: Option<&Bound<'_, PyAny>>,
    on_change: Option<Py<PyAny>>,
) -> PyResult<PyWidget> {
    let selected = selected.map(binding_number_from_py).transpose()?;
    let action = on_change.map(|callback| {
        BindingSelectAction::new(move |index, value| {
            Python::attach(|py| {
                callback
                    .call1(py, (index, value))
                    .map(|_| ())
                    .map_err(|error| ForeignCallbackFailure::new(error.to_string()))
            })
        })
    });
    Ok(PyWidget::from_binding(BindingWidget::tab_bar(
        binding_text_from_py(name)?,
        tabs,
        selected,
        action,
    )))
}

#[pyfunction(name = "Tabs")]
#[pyo3(signature = (name, tabs, selected=None))]
pub fn py_tabs(
    name: &Bound<'_, PyAny>,
    tabs: Vec<String>,
    selected: Option<&Bound<'_, PyAny>>,
) -> PyResult<PyWidget> {
    Ok(PyWidget::from_binding(BindingWidget::tabs(
        binding_text_from_py(name)?,
        tabs,
        selected.map(binding_number_from_py).transpose()?,
    )))
}

#[pyfunction(name = "Dialog")]
#[pyo3(signature = (title, content, shown=None))]
pub fn py_dialog(
    title: &Bound<'_, PyAny>,
    content: PyRef<'_, PyWidget>,
    shown: Option<&Bound<'_, PyAny>>,
) -> PyResult<PyWidget> {
    let shown = shown
        .map(binding_bool_from_py)
        .transpose()?
        .unwrap_or(BindingBool::Static(true));
    Ok(PyWidget::from_binding(BindingWidget::dialog(
        binding_text_from_py(title)?,
        content.binding_widget()?,
        shown,
    )))
}
