"use strict";

// Generated by `cargo xtask bindings generate` from bindings/widgets.sui.
// Do not edit by hand.

function decorateApi(native) {
  const factories = {
    label(value) {
      return native.Label(value);
    },
    button(label, options = {}) {
      return native.Button(label, options.onPress);
    },
    icon(glyph, options = {}) {
      return native.Icon(glyph, options.label, options.size, options.color);
    },
    iconButton(glyph, label, options = {}) {
      return native.IconButton(glyph, label, options.selected, options.enabled, options.size, options.iconSize, options.description, options.onPress);
    },
    link(label, url, options = {}) {
      return native.Link(label, url, options.semanticName, options.enabled, options.onOpen);
    },
    checkbox(label, options = {}) {
      return native.Checkbox(label, options.checked, options.onToggle);
    },
    switchControl(label, options = {}) {
      return native.Switch(label, options.on, options.onToggle);
    },
    radioButton(label, options = {}) {
      return native.RadioButton(label, options.selected, options.onSelect);
    },
    radioGroup(name, options, config = {}) {
      return native.RadioGroup(name, options, config.selected, config.onChange);
    },
    segmentedControl(name, items, options = {}) {
      return native.SegmentedControl(name, items, options.selected, options.onChange);
    },
    breadcrumb(name, items, options = {}) {
      return native.Breadcrumb(name, items, options.current, options.onActivate);
    },
    pathBar(name, items, options = {}) {
      return native.PathBar(name, items, options.current, options.onActivate);
    },
    listView(name, items, options = {}) {
      return native.ListView(name, items, options.selected, options.onChange);
    },
    table(name, columns, rows, options = {}) {
      return native.Table(name, columns, rows, options.selected, options.onChange);
    },
    dataGrid(name, columns, rows, options = {}) {
      return native.DataGrid(name, columns, rows, options.selected, options.onChange);
    },
    slider(name, options = {}) {
      return native.Slider(name, options.value, options.min, options.max, options.step, options.onChange);
    },
    numberInput(name, options = {}) {
      return native.NumberInput(name, options.value, options.min, options.max, options.step, options.precision, options.onChange);
    },
    select(name, options, config = {}) {
      return native.Select(name, options, config.selected, config.placeholder, config.onChange);
    },
    progressBar(name, options = {}) {
      return native.ProgressBar(name, options.value, options.min, options.max, options.showValue);
    },
    signalMeter(name, options = {}) {
      return native.SignalMeter(name, options.active, options.description, options.bars, options.size);
    },
    statusBadge(label, options = {}) {
      return native.StatusBadge(label, options.tone, options.icon, options.minWidth);
    },
    statusBar(segments, options = {}) {
      return native.StatusBar(segments, options.name, options.description, options.height);
    },
    detailRow(label, value, options = {}) {
      return native.DetailRow(label, value, options.maxValueLines);
    },
    busyIndicator(name, options = {}) {
      return native.BusyIndicator(name, options.label, options.size);
    },
    textInput(name, options = {}) {
      return native.TextInput(name, options.value, options.placeholder, options.onChange);
    },
    textArea(name, options = {}) {
      return native.TextArea(name, options.value, options.placeholder, options.onChange);
    },
    richText(spans, options = {}) {
      return native.RichText(spans, options.semanticName, options.minWidth, options.minHeight);
    },
    richDocumentView(document, options = {}) {
      return native.RichDocumentView(document, options.onLink, options.onImage, options.onAttachment);
    },
    image(image, options = {}) {
      return native.Image(image, options.label, options.fit, options.size);
    },
    colorSwatch(name, color, options = {}) {
      return native.ColorSwatch(name, color, options.size, options.readOnly, options.onPress);
    },
    separator(options = {}) {
      return native.Separator(options.axis, options.name, options.inset, options.thickness, options.length);
    },
    emptyState(title, description, options = {}) {
      return native.EmptyState(title, description, options.name, options.detail, options.icon, options.action, options.background, options.transparent);
    },
    surface(child, options = {}) {
      return native.Surface(child, options.role, options.name, options.border, options.elevation, options.radius, options.padding, options.fillWidth, options.fillHeight);
    },
    toolbar(children, options = {}) {
      return native.Toolbar(children, options.axis, options.name, options.extent, options.padding, options.spacing, options.background, options.divider);
    },
    column(children, options = {}) {
      return native.Column(children, options.gap);
    },
    row(children, options = {}) {
      return native.Row(children, options.gap);
    },
    grid(children, options = {}) {
      return native.Grid(children, options.columns, options.name, options.gap, options.columnGap, options.rowGap);
    },
    aspectRatio(child, ratio, options = {}) {
      return native.AspectRatio(child, ratio, options.fit, options.horizontal, options.vertical);
    },
    safeArea(child, options = {}) {
      return native.SafeArea(child, options.edges, options.minimumLeft, options.minimumTop, options.minimumRight, options.minimumBottom);
    },
    layoutTransition(child, options = {}) {
      return native.LayoutTransition(child, options.duration, options.easing);
    },
    adaptiveView(compact, medium, expanded, options = {}) {
      return native.AdaptiveView(compact, medium, expanded, options.mediumBreakpoint, options.expandedBreakpoint, options.onClassChange);
    },
    constraintView(cases, fallback) {
      return native.ConstraintView(cases, fallback);
    },
    responsiveSidebar(state, sidebar, content, options = {}) {
      return native.ResponsiveSidebar(state, sidebar, content, options.name, options.mediumBreakpoint, options.expandedBreakpoint, options.railWidth, options.overlayWidth, options.dismissOnScrim, options.onModeChange);
    },
    masterDetail(state, master, detail, options = {}) {
      return native.MasterDetail(state, master, detail, options.mediumBreakpoint, options.expandedBreakpoint, options.masterWidth);
    },
    overlayHost(child) {
      return native.OverlayHost(child);
    },
    notificationHost(center, options = {}) {
      return native.NotificationHost(center, options.width);
    },
    canvas(name, options = {}) {
      return native.Canvas(name, options.shapes, options.viewport, options.drawStroke, options.desiredSize);
    },
    canvasRuler(axis, name, documentSize, options = {}) {
      return native.CanvasRuler(axis, name, documentSize, options.viewport, options.viewportSize, options.extent);
    },
    pixelCanvas(state, name, width, height, options = {}) {
      return native.PixelCanvas(state, name, width, height, options.paperColor, options.desiredSize, options.viewport, options.fitOnFirstLayout, options.pixels);
    },
    dragDropHost(scope, child, options = {}) {
      return native.DragDropHost(scope, child, options.onExternalHover, options.onExternalDrop, options.onExternalCancel);
    },
    draggable(scope, child, payload, options = {}) {
      return native.Draggable(scope, child, payload, options.effect, options.previewLabel, options.threshold, options.onStart, options.onEnd);
    },
    dropTarget(scope, child, options = {}) {
      return native.DropTarget(scope, child, options.effect, options.onDrop, options.onHoverChange);
    },
    virtualList(name, model, options = {}) {
      return native.VirtualList(name, model, options.estimatedRowHeight, options.spacing, options.padding, options.rowPadding, options.overscanViewports, options.cacheCapacity, options.selectable, options.transparent, options.stickToEnd, options.overlayScrollBars, options.onChange, options.onNearStart, options.onNearEnd);
    },
    scrollView(child, options = {}) {
      return native.ScrollView(child, options.axes, options.name);
    },
    externalSurface(texture, options = {}) {
      return native.ExternalSurface(texture, options.desiredSize, options.name);
    },
    treeView(name, items, options = {}) {
      return native.TreeView(name, items, options.selected, options.onChange);
    },
    layerList(name, items, options = {}) {
      return native.LayerList(name, items, options.selected, options.onChange);
    },
    menu(name, items, options = {}) {
      return native.Menu(name, items, options.highlighted, options.onActivate);
    },
    contextMenu(name, trigger, items, options = {}) {
      return native.ContextMenu(name, trigger, items, options.onActivate);
    },
    tabBar(name, tabs, options = {}) {
      return native.TabBar(name, tabs, options.selected, options.onChange);
    },
    tabs(name, tabs, options = {}) {
      return native.Tabs(name, tabs, options.selected);
    },
    dialog(title, content, options = {}) {
      return native.Dialog(title, content, options.shown);
    },
    commandPalette(name, content, options = {}) {
      return native.CommandPalette(name, content, options.description, options.shown, options.maxWidth, options.onDismiss);
    },
    padding(child, options = {}) {
      return native.Padding(child, options.padding, options.top, options.right, options.bottom, options.fillChildWidth, options.fillChildHeight);
    },
    align(child, options = {}) {
      return native.Align(child, options.horizontal, options.vertical);
    },
    background(child, color) {
      return native.Background(child, color);
    },
    sizedBox(options = {}) {
      return native.SizedBox(options.child, options.width, options.height);
    },
    stack(children, options = {}) {
      return native.Stack(children, options.axis, options.spacing, options.alignment);
    },
    semanticRegion(name, child, options = {}) {
      return native.SemanticRegion(name, child, options.description, options.role);
    },
    formRow(label, control, options = {}) {
      return native.FormRow(label, control, options.stacked, options.labelWidth, options.controlWidth, options.gap);
    },
    fieldGroup(children, options = {}) {
      return native.FieldGroup(children, options.spacing, options.padding, options.maxWidth, options.fillWidth);
    },
    formSection(title, child, options = {}) {
      return native.FormSection(title, child, options.description, options.headerAction, options.padding, options.bodyGap, options.headerGap, options.maxWidth, options.fillWidth, options.radius, options.elevation);
    },
    panelSection(title, child, options = {}) {
      return native.PanelSection(title, child, options.headerAction, options.gap, options.actionGap, options.collapsible, options.expanded);
    },
    dockPanel(title, child, options = {}) {
      return native.DockPanel(title, child, options.name, options.headerHeight, options.padding, options.background, options.headerBackground);
    },
    statusBarHost(content, statusBar) {
      return native.StatusBarHost(content, statusBar);
    },
    tooltip(text, child, options = {}) {
      return native.Tooltip(text, child, options.placement);
    },
    popover(name, trigger, content, options = {}) {
      return native.Popover(name, trigger, content, options.open);
    },
    toolPalette(name, items, options = {}) {
      return native.ToolPalette(name, items, options.selected, options.axis, options.onChange, options.extent, options.padding, options.spacing, options.itemSize, options.iconSize, options.background, options.divider);
    },
    presetStrip(name, presets, options = {}) {
      return native.PresetStrip(name, presets, options.selected, options.onChange, options.itemWidth, options.itemHeight, options.gap);
    },
    browserTabBar(name, tabs, options = {}) {
      return native.BrowserTabBar(name, tabs, options.selected, options.onChange, options.onClose);
    },
    colorPalette(name, swatches, options = {}) {
      return native.ColorPalette(name, swatches, options.selected, options.onChange, options.columns, options.swatchSize, options.gap);
    },
    colorPicker(name, options = {}) {
      return native.ColorPicker(name, options.color, options.onChange, options.showAlpha, options.compact);
    },
    simpleColorPicker(name, options = {}) {
      return native.SimpleColorPicker(name, options.color, options.mode, options.onChange, options.showAlpha, options.compact);
    },
    passwordInput(name, options = {}) {
      return native.PasswordInput(name, options.value, options.placeholder, options.onChange);
    },
    dateTimeInput(name, options = {}) {
      return native.DateTimeInput(name, options.value, options.placeholder, options.onChange);
    },
    actionCard(title, description, options = {}) {
      return native.ActionCard(title, description, options.icon, options.tone, options.enabled, options.onPress);
    },
    brushPreview(name, spec, options = {}) {
      return native.BrushPreview(name, spec, options.kind, options.size);
    },
    commandGroup(name, children, options = {}) {
      return native.CommandGroup(name, children, options.axis, options.padding, options.spacing, options.cornerRadius, options.background, options.border);
    },
    coverageDots(name, current, target, options = {}) {
      return native.CoverageDots(name, current, target, options.tone, options.maxDots, options.showLabel, options.minWidth);
    },
    dock(body, options = {}) {
      return native.Dock(body, options.top, options.topHeight, options.bottom, options.bottomHeight, options.fallbackWidth, options.fallbackBodyHeight);
    },
    fixedPaneSplit(first, divider, second, options = {}) {
      return native.FixedPaneSplit(first, divider, second, options.axis, options.fixedPane, options.fixedExtent, options.dividerExtent, options.fallbackFlexibleExtent);
    },
    framedField(child, options = {}) {
      return native.FramedField(child, options.name, options.description, options.padding, options.minHeight, options.fillWidth, options.focused, options.invalid);
    },
    measuredBottomDock(body, bottom, options = {}) {
      return native.MeasuredBottomDock(body, bottom, options.fallbackSize);
    },
    placementBadge(label, options = {}) {
      return native.PlacementBadge(label, options.icon, options.tone, options.current, options.target, options.minWidth);
    },
    propertyRow(label, control, options = {}) {
      return native.PropertyRow(label, control, options.stacked, options.labelWidth, options.controlWidth, options.gap);
    },
    sectionLabel(label, options = {}) {
      return native.SectionLabel(label, options.semanticName, options.color);
    },
    sideSheet(title, body, options = {}) {
      return native.SideSheet(title, body, options.description, options.shown, options.modal, options.dismissOnScrim, options.placement, options.width, options.headerAction, options.actions, options.onDismiss);
    },
    bottomSheet(title, body, options = {}) {
      return native.BottomSheet(title, body, options.description, options.shown, options.modal, options.dismissOnScrim, options.height, options.headerAction, options.actions, options.onDismiss);
    },
    splitView(first, second, options = {}) {
      return native.SplitView(first, second, options.axis, options.name, options.ratio, options.minFirst, options.minSecond, options.dividerThickness, options.onChange);
    },
    switchView(children, options = {}) {
      return native.SwitchView(children, options.selected);
    },
    trailingSlotRow(body, trailing, options = {}) {
      return native.TrailingSlotRow(body, trailing, options.trailingWidth, options.trailingHeight, options.gap);
    },
    floatingWorkspace(state, views, options = {}) {
      return native.FloatingWorkspace(state, views, options.name);
    },
    dockWorkspace(state, panels, options = {}) {
      return native.DockWorkspace(state, panels, options.name);
    },
    floatingStack(windows, options = {}) {
      return native.FloatingStack(windows, options.name);
    },
    virtualScrollView(children, options = {}) {
      return native.VirtualScrollView(children, options.name, options.padding, options.spacing);
    },
    reorderableList(name, children, options = {}) {
      return native.ReorderableList(name, children, options.spacing, options.dragThreshold, options.previewLabel, options.onReorder);
    },
  };

  return Object.assign(native, factories);
}

module.exports = { decorateApi };
