#![forbid(unsafe_code)]

use std::{
    collections::{BTreeMap, HashSet},
    env, fs,
    path::PathBuf,
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let icons_dir = manifest_dir.join("assets").join("icons");
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let mut files = fs::read_dir(&icons_dir)
        .expect("Lucide icons directory should exist")
        .filter_map(|entry| {
            let entry = entry.expect("icon directory entry should be readable");
            let path = entry.path();
            (path.extension().and_then(|extension| extension.to_str()) == Some("svg")).then(|| {
                path.file_stem()
                    .and_then(|stem| stem.to_str())
                    .expect("Lucide icon filename should be UTF-8")
                    .to_string()
            })
        })
        .collect::<Vec<_>>();
    files.sort();

    let mut variants = BTreeMap::new();
    let mut seen = HashSet::new();
    for file_stem in files {
        let mut variant = pascal_case_identifier(&file_stem);
        if !seen.insert(variant.clone()) {
            let mut suffix = 2;
            while !seen.insert(format!("{variant}{suffix}")) {
                suffix += 1;
            }
            variant = format!("{variant}{suffix}");
        }
        variants.insert(file_stem, variant);
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let generated = out_dir.join("generated.rs");
    fs::write(generated, render_generated(&variants)).expect("generated Lucide table should write");
}

fn pascal_case_identifier(file_stem: &str) -> String {
    let mut identifier = String::new();
    for part in file_stem
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            if identifier.is_empty() && first.is_ascii_digit() {
                identifier.push_str("Icon");
            }
            identifier.push(first.to_ascii_uppercase());
            for ch in chars {
                identifier.push(ch.to_ascii_lowercase());
            }
        }
    }

    if identifier.is_empty() {
        "Icon".to_string()
    } else {
        identifier
    }
}

fn render_generated(variants: &BTreeMap<String, String>) -> String {
    let mut source = String::new();
    source.push_str("// Generated by build.rs from assets/icons.\n");
    source.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    source.push_str("#[repr(u16)]\n");
    source.push_str("pub enum LucideIcon {\n");
    for variant in variants.values() {
        source.push_str("    ");
        source.push_str(variant);
        source.push_str(",\n");
    }
    source.push_str("}\n\n");

    source.push_str("impl LucideIcon {\n");
    source.push_str("    pub const fn name(self) -> &'static str {\n");
    source.push_str("        match self {\n");
    for (file_stem, variant) in variants {
        source.push_str("            Self::");
        source.push_str(variant);
        source.push_str(" => \"");
        source.push_str(file_stem);
        source.push_str("\",\n");
    }
    source.push_str("        }\n");
    source.push_str("    }\n\n");

    source.push_str("    pub const fn file_name(self) -> &'static str {\n");
    source.push_str("        match self {\n");
    for (file_stem, variant) in variants {
        source.push_str("            Self::");
        source.push_str(variant);
        source.push_str(" => \"");
        source.push_str(file_stem);
        source.push_str(".svg\",\n");
    }
    source.push_str("        }\n");
    source.push_str("    }\n\n");

    source.push_str("    pub const fn handle(self) -> sui_core::ImageHandle {\n");
    source.push_str(
        "        sui_core::ImageHandle::new(crate::LUCIDE_IMAGE_HANDLE_BASE + self as u64)\n",
    );
    source.push_str("    }\n\n");

    source.push_str("    pub const fn svg(self) -> &'static [u8] {\n");
    source.push_str("        match self {\n");
    for (file_stem, variant) in variants {
        source.push_str("            Self::");
        source.push_str(variant);
        source
            .push_str(" => include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/");
        source.push_str(file_stem);
        source.push_str(".svg\")),\n");
    }
    source.push_str("        }\n");
    source.push_str("    }\n\n");

    source.push_str("    pub const fn resource(self) -> sui_runtime::EmbeddedSvgImageResource {\n");
    source.push_str(
        "        sui_runtime::EmbeddedSvgImageResource::new(self.handle(), self.svg())\n",
    );
    source.push_str("    }\n");
    source.push_str("}\n\n");

    source.push_str("pub const ALL_ICONS: &[LucideIcon] = &[\n");
    for variant in variants.values() {
        source.push_str("    LucideIcon::");
        source.push_str(variant);
        source.push_str(",\n");
    }
    source.push_str("];\n");

    source
}
