#![forbid(unsafe_code)]

use std::{
    collections::{BTreeMap, HashSet},
    env, fs,
    path::PathBuf,
};

#[derive(Debug, Clone, Copy)]
enum NativePathCommand {
    MoveTo(f64, f64),
    LineTo(f64, f64),
    QuadTo(f64, f64, f64, f64),
    CubicTo(f64, f64, f64, f64, f64, f64),
    Close,
}

#[derive(Debug, Default)]
struct NativeIconData {
    stroke: Vec<NativePathCommand>,
    fill: Vec<NativePathCommand>,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let icons_dir = manifest_dir.join("assets").join("icons");
    println!("cargo:rerun-if-changed={}", icons_dir.display());

    let mut files = fs::read_dir(&icons_dir)
        .expect("Lucide icons directory should exist")
        .filter_map(|entry| {
            let entry = entry.expect("icon directory entry should be readable");
            let path = entry.path();
            (path.extension().and_then(|extension| extension.to_str()) == Some("svg")).then(|| {
                path.file_stem()
                    .and_then(|stem| stem.to_str())
                    .expect("Lucide icon filename should be UTF-8")
                    .to_string()
            })
        })
        .collect::<Vec<_>>();
    files.sort();

    let mut variants = BTreeMap::new();
    let mut seen = HashSet::new();
    for file_stem in files {
        let mut variant = pascal_case_identifier(&file_stem);
        if !seen.insert(variant.clone()) {
            let mut suffix = 2;
            while !seen.insert(format!("{variant}{suffix}")) {
                suffix += 1;
            }
            variant = format!("{variant}{suffix}");
        }
        variants.insert(file_stem, variant);
    }

    let icon_data = variants
        .keys()
        .map(|file_stem| {
            let path = icons_dir.join(format!("{file_stem}.svg"));
            let svg = fs::read_to_string(&path)
                .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
            (file_stem.clone(), parse_native_icon(file_stem, &svg))
        })
        .collect::<BTreeMap<_, _>>();
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let generated = out_dir.join("generated.rs");
    fs::write(generated, render_generated(&variants, &icon_data))
        .expect("generated Lucide table should write");
}

fn pascal_case_identifier(file_stem: &str) -> String {
    let mut identifier = String::new();
    for part in file_stem
        .split(|ch: char| !ch.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
    {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            if identifier.is_empty() && first.is_ascii_digit() {
                identifier.push_str("Icon");
            }
            identifier.push(first.to_ascii_uppercase());
            for ch in chars {
                identifier.push(ch.to_ascii_lowercase());
            }
        }
    }

    if identifier.is_empty() {
        "Icon".to_string()
    } else {
        identifier
    }
}

fn render_generated(
    variants: &BTreeMap<String, String>,
    icon_data: &BTreeMap<String, NativeIconData>,
) -> String {
    let mut source = String::new();
    source.push_str("// Generated by build.rs from assets/icons.\n");
    source.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    source.push_str("#[repr(u16)]\n");
    source.push_str("pub enum LucideIcon {\n");
    for variant in variants.values() {
        source.push_str("    ");
        source.push_str(variant);
        source.push_str(",\n");
    }
    source.push_str("}\n\n");

    source.push_str("impl LucideIcon {\n");
    source.push_str("    pub const fn name(self) -> &'static str {\n");
    source.push_str("        match self {\n");
    for (file_stem, variant) in variants {
        source.push_str("            Self::");
        source.push_str(variant);
        source.push_str(" => \"");
        source.push_str(file_stem);
        source.push_str("\",\n");
    }
    source.push_str("        }\n");
    source.push_str("    }\n\n");

    source.push_str("    pub const fn file_name(self) -> &'static str {\n");
    source.push_str("        match self {\n");
    for (file_stem, variant) in variants {
        source.push_str("            Self::");
        source.push_str(variant);
        source.push_str(" => \"");
        source.push_str(file_stem);
        source.push_str(".svg\",\n");
    }
    source.push_str("        }\n");
    source.push_str("    }\n\n");

    source.push_str("    pub const fn handle(self) -> sui_core::ImageHandle {\n");
    source.push_str(
        "        sui_core::ImageHandle::new(crate::LUCIDE_IMAGE_HANDLE_BASE + self as u64)\n",
    );
    source.push_str("    }\n\n");

    source.push_str("    pub const fn svg(self) -> &'static [u8] {\n");
    source.push_str("        match self {\n");
    for (file_stem, variant) in variants {
        source.push_str("            Self::");
        source.push_str(variant);
        source
            .push_str(" => include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/");
        source.push_str(file_stem);
        source.push_str(".svg\")),\n");
    }
    source.push_str("        }\n");
    source.push_str("    }\n\n");

    source.push_str("    pub const fn resource(self) -> sui_runtime::EmbeddedSvgImageResource {\n");
    source.push_str(
        "        sui_runtime::EmbeddedSvgImageResource::new(self.handle(), self.svg())\n",
    );
    source.push_str("    }\n");
    // SVG coordinates such as 3.14 and 6.28 are data, not approximations of mathematical
    // constants. Keep Clippy's approximation lint enabled for handwritten code while avoiding
    // false positives in this generated lookup table.
    source.push_str("\n    #[allow(clippy::approx_constant)]\n");
    source.push_str("    pub const fn path_data(self) -> crate::LucidePathData {\n");
    source.push_str("        match self {\n");
    for (file_stem, variant) in variants {
        let data = &icon_data[file_stem];
        source.push_str("            Self::");
        source.push_str(variant);
        source.push_str(" => crate::LucidePathData { stroke: &[\n");
        render_path_commands(&mut source, &data.stroke);
        source.push_str("            ], fill: &[\n");
        render_path_commands(&mut source, &data.fill);
        source.push_str("            ] },\n");
    }
    source.push_str("        }\n");
    source.push_str("    }\n");
    source.push_str("}\n\n");

    source.push_str("pub const ALL_ICONS: &[LucideIcon] = &[\n");
    for variant in variants.values() {
        source.push_str("    LucideIcon::");
        source.push_str(variant);
        source.push_str(",\n");
    }
    source.push_str("];\n");

    source
}

fn parse_native_icon(name: &str, svg: &str) -> NativeIconData {
    let document = roxmltree::Document::parse(svg)
        .unwrap_or_else(|error| panic!("failed to parse Lucide icon {name}: {error}"));
    let root = document.root_element();
    let mut data = NativeIconData::default();
    for node in root.children().filter(roxmltree::Node::is_element) {
        let commands = shape_commands(name, node);
        if commands.is_empty() {
            continue;
        }
        if node.attribute("stroke") != Some("none") {
            data.stroke.extend(commands.iter().copied());
        }
        if node.attribute("fill") == Some("currentColor") {
            data.fill.extend(commands);
        }
    }
    data
}

fn shape_commands(name: &str, node: roxmltree::Node<'_, '_>) -> Vec<NativePathCommand> {
    match node.tag_name().name() {
        "path" => svgtypes::SimplifyingPathParser::from(required_attribute(name, node, "d"))
            .map(|segment| {
                let segment = segment
                    .unwrap_or_else(|error| panic!("invalid path in Lucide icon {name}: {error}"));
                match segment {
                    svgtypes::SimplePathSegment::MoveTo { x, y } => NativePathCommand::MoveTo(x, y),
                    svgtypes::SimplePathSegment::LineTo { x, y } => NativePathCommand::LineTo(x, y),
                    svgtypes::SimplePathSegment::CurveTo {
                        x1,
                        y1,
                        x2,
                        y2,
                        x,
                        y,
                    } => NativePathCommand::CubicTo(x1, y1, x2, y2, x, y),
                    svgtypes::SimplePathSegment::Quadratic { x1, y1, x, y } => {
                        NativePathCommand::QuadTo(x1, y1, x, y)
                    }
                    svgtypes::SimplePathSegment::ClosePath => NativePathCommand::Close,
                }
            })
            .collect(),
        "circle" => ellipse_commands(
            number_attribute(name, node, "cx"),
            number_attribute(name, node, "cy"),
            number_attribute(name, node, "r"),
            number_attribute(name, node, "r"),
        ),
        "ellipse" => ellipse_commands(
            number_attribute(name, node, "cx"),
            number_attribute(name, node, "cy"),
            number_attribute(name, node, "rx"),
            number_attribute(name, node, "ry"),
        ),
        "line" => vec![
            NativePathCommand::MoveTo(
                number_attribute(name, node, "x1"),
                number_attribute(name, node, "y1"),
            ),
            NativePathCommand::LineTo(
                number_attribute(name, node, "x2"),
                number_attribute(name, node, "y2"),
            ),
        ],
        "rect" => rect_commands(name, node),
        "polyline" | "polygon" => {
            let mut points = svgtypes::PointsParser::from(required_attribute(name, node, "points"))
                .collect::<Vec<_>>();
            if points.is_empty() {
                return Vec::new();
            }
            let first = points.remove(0);
            let mut commands = vec![NativePathCommand::MoveTo(first.0, first.1)];
            commands.extend(
                points
                    .into_iter()
                    .map(|(x, y)| NativePathCommand::LineTo(x, y)),
            );
            if node.tag_name().name() == "polygon" {
                commands.push(NativePathCommand::Close);
            }
            commands
        }
        other => panic!("unsupported <{other}> in Lucide icon {name}"),
    }
}

fn ellipse_commands(cx: f64, cy: f64, rx: f64, ry: f64) -> Vec<NativePathCommand> {
    const KAPPA: f64 = 0.552_284_749_830_793_6;
    let kx = rx * KAPPA;
    let ky = ry * KAPPA;
    vec![
        NativePathCommand::MoveTo(cx + rx, cy),
        NativePathCommand::CubicTo(cx + rx, cy + ky, cx + kx, cy + ry, cx, cy + ry),
        NativePathCommand::CubicTo(cx - kx, cy + ry, cx - rx, cy + ky, cx - rx, cy),
        NativePathCommand::CubicTo(cx - rx, cy - ky, cx - kx, cy - ry, cx, cy - ry),
        NativePathCommand::CubicTo(cx + kx, cy - ry, cx + rx, cy - ky, cx + rx, cy),
        NativePathCommand::Close,
    ]
}

fn rect_commands(name: &str, node: roxmltree::Node<'_, '_>) -> Vec<NativePathCommand> {
    let x = optional_number_attribute(name, node, "x").unwrap_or(0.0);
    let y = optional_number_attribute(name, node, "y").unwrap_or(0.0);
    let width = number_attribute(name, node, "width");
    let height = number_attribute(name, node, "height");
    let rx = optional_number_attribute(name, node, "rx");
    let ry = optional_number_attribute(name, node, "ry");
    let rx = rx.or(ry).unwrap_or(0.0).min(width * 0.5);
    let ry = ry.or(Some(rx)).unwrap_or(0.0).min(height * 0.5);
    if rx <= 0.0 || ry <= 0.0 {
        return vec![
            NativePathCommand::MoveTo(x, y),
            NativePathCommand::LineTo(x + width, y),
            NativePathCommand::LineTo(x + width, y + height),
            NativePathCommand::LineTo(x, y + height),
            NativePathCommand::Close,
        ];
    }

    const KAPPA: f64 = 0.552_284_749_830_793_6;
    let kx = rx * KAPPA;
    let ky = ry * KAPPA;
    vec![
        NativePathCommand::MoveTo(x + rx, y),
        NativePathCommand::LineTo(x + width - rx, y),
        NativePathCommand::CubicTo(
            x + width - rx + kx,
            y,
            x + width,
            y + ry - ky,
            x + width,
            y + ry,
        ),
        NativePathCommand::LineTo(x + width, y + height - ry),
        NativePathCommand::CubicTo(
            x + width,
            y + height - ry + ky,
            x + width - rx + kx,
            y + height,
            x + width - rx,
            y + height,
        ),
        NativePathCommand::LineTo(x + rx, y + height),
        NativePathCommand::CubicTo(
            x + rx - kx,
            y + height,
            x,
            y + height - ry + ky,
            x,
            y + height - ry,
        ),
        NativePathCommand::LineTo(x, y + ry),
        NativePathCommand::CubicTo(x, y + ry - ky, x + rx - kx, y, x + rx, y),
        NativePathCommand::Close,
    ]
}

fn required_attribute<'a>(name: &str, node: roxmltree::Node<'a, '_>, attribute: &str) -> &'a str {
    node.attribute(attribute)
        .unwrap_or_else(|| panic!("Lucide icon {name} is missing {attribute}"))
}

fn number_attribute(name: &str, node: roxmltree::Node<'_, '_>, attribute: &str) -> f64 {
    optional_number_attribute(name, node, attribute)
        .unwrap_or_else(|| panic!("Lucide icon {name} is missing {attribute}"))
}

fn optional_number_attribute(
    name: &str,
    node: roxmltree::Node<'_, '_>,
    attribute: &str,
) -> Option<f64> {
    node.attribute(attribute).map(|value| {
        value.parse::<f64>().unwrap_or_else(|error| {
            panic!("invalid {attribute}={value:?} in Lucide icon {name}: {error}")
        })
    })
}

fn render_path_commands(source: &mut String, commands: &[NativePathCommand]) {
    for command in commands {
        source.push_str("                ");
        match command {
            NativePathCommand::MoveTo(x, y) => {
                source.push_str(&format!(
                    "crate::LucidePathCommand::MoveTo({}, {}),\n",
                    f32_literal(*x),
                    f32_literal(*y),
                ));
            }
            NativePathCommand::LineTo(x, y) => {
                source.push_str(&format!(
                    "crate::LucidePathCommand::LineTo({}, {}),\n",
                    f32_literal(*x),
                    f32_literal(*y),
                ));
            }
            NativePathCommand::QuadTo(x1, y1, x, y) => {
                source.push_str(&format!(
                    "crate::LucidePathCommand::QuadTo({}, {}, {}, {}),\n",
                    f32_literal(*x1),
                    f32_literal(*y1),
                    f32_literal(*x),
                    f32_literal(*y),
                ));
            }
            NativePathCommand::CubicTo(x1, y1, x2, y2, x, y) => {
                source.push_str(&format!(
                    "crate::LucidePathCommand::CubicTo({}, {}, {}, {}, {}, {}),\n",
                    f32_literal(*x1),
                    f32_literal(*y1),
                    f32_literal(*x2),
                    f32_literal(*y2),
                    f32_literal(*x),
                    f32_literal(*y),
                ));
            }
            NativePathCommand::Close => {
                source.push_str("crate::LucidePathCommand::Close,\n");
            }
        }
    }
}

fn f32_literal(value: f64) -> String {
    format!("{:?}", value as f32)
}
